server:
  port: 8082
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/wsm
    username: postgres
    password: postgres
    driver-class-name: 'org.postgresql.Driver'